services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
    depends_on:
      - db

volumes:
  db_data:
